# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "015ee793deb14046b31e6371706fb3aa"
name = "wjiangstore4sale-app"
handle = "wjiangstore4sale-app"
application_url = "https://surveys-highlighted-pixel-places.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_draft_orders,read_customers,write_files"

[auth]
redirect_urls = [
  "https://surveys-highlighted-pixel-places.trycloudflare.com/auth/callback",
  "https://surveys-highlighted-pixel-places.trycloudflare.com/auth/shopify/callback",
  "https://surveys-highlighted-pixel-places.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
